name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            # 진단을 위해 set -e를 잠시 비활성화하여 스크립트가 중간에 죽지 않게 함
            # set -e
            
            cd /home/ubuntu/github-action-practice
            
            echo "--- Starting Diagnosis ---"
            
            # 문제가 되는 동일한 패턴으로 어떤 프로세스가 검색되는지 확인
            PIDS_FOUND=$(pgrep -f "java -jar.*github-action-practice.*\.jar")
            
            if [ -z "$PIDS_FOUND" ]; then
                echo "No matching processes were found by pgrep."
            else
                echo "pgrep found the following PID(s): $PIDS_FOUND"
                echo "--- Displaying full process info for these PIDs ---"
                # 찾은 PID들의 상세 정보를 출력
                ps -f -p $PIDS_FOUND
                echo "----------------------------------------------------"
            fi
            
            echo "--- Diagnosis Finished ---"
