name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -e
            
            cd /home/ubuntu/github-action-practice
            
            echo "Start deployment"
            echo "Pull repository"
            git pull origin main
            
            echo "Gradle Build"
            chmod +x ./gradlew
            ./gradlew build
            
            CURRENT_PID=$(pgrep -f "github-action-practice.*\.jar")
            
            if [ -z "$CURRENT_PID" ]; then
                echo "No running application"
            else
                echo "Terminate running application: $CURRENT_PID"
                kill -15 $CURRENT_PID
                sleep 5
            fi
            
            echo "Deploy new application"
            
            JAR_FILE=$(ls build/libs/github-action-practice*.jar | grep -v "\-plain.jar$" | head -n 1)
            
            LOG_PATH="/home/ubuntu/github-action-practice/logs/server_log_$(date +%Y-%m-%d).txt"
            
            nohup java -jar --spring.profiles.active=dev "$JAR_FILE" >> "$LOG_PATH" 2>&1 &
            
            find build/libs -type f -name "*.jar" -mtime +3 -delete
            
            echo "Deployment complete"
