name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -e
            
            cd /home/ubuntu/github-action-practice
            
            echo "Start deployment"
            git pull origin main
            
            echo "Gradle Build (skipping tests)"
            chmod +x ./gradlew
            ./gradlew build -x test
            
            echo "--- Terminating existing process if any ---"
            pkill -f "java -jar.*github-action-practice.*\.jar" || true
            echo "Waiting 5 seconds for shutdown..."
            sleep 5
            
            echo "Deploy new application"
            
            JAR_FILE=$(find build/libs -name 'github-action-practice-*.jar' ! -name '*-plain.jar' -print -quit)
            
            if [ -z "$JAR_FILE" ]; then
                echo "ERROR: JAR file not found."
                ls -l build/libs/
                exit 1
            fi
            
            echo "Found JAR file to deploy: $JAR_FILE"
            
            LOG_PATH="/home/ubuntu/github-action-practice/logs/server_log_$(date +%Y-%m-%d).txt"
            
            mkdir -p $(dirname "$LOG_PATH")
            
            # ✨ 여기가 최종 수정된 부분 ✨
            # JAR 파일 이름 뒤에 스프링 옵션이 오도록 순서를 수정
            nohup java -jar "$JAR_FILE" --spring.profiles.active=dev >> "$LOG_PATH" 2>&1 &
            
            echo "Deployment complete"
